---
name: steep
description: |
  Static type checker for Ruby
homepage: https://github.com/soutaro/steep
licenses:
  - MIT
languages:
  - Ruby
categories:
  - LSP

source:
  id: pkg:gem/steep@1.6.0

schemas:
  lsp: vscode:https://raw.githubusercontent.com/soutaro/steep-vscode/master/package.json

bin:
  steep: gem:steep
